doctrine_migrations:
    migrations_paths:
        # namespace is arbitrary but should be different from App\Migrations
        # as migrations classes should NOT be autoloaded
        'DoctrineMigrations': '%kernel.project_dir%/migrations/users'
        'DoctrineMigrationsOrders': '%kernel.project_dir%/migrations/orders'
        'DoctrineMigrationsErp': '%kernel.project_dir%/migrations/erp'
        'DoctrineMigrationsProducts': '%kernel.project_dir%/migrations/products'
        'DoctrineMigrationsPromotions': '%kernel.project_dir%/migrations/promotions'
        'DoctrineMigrationsReviews': '%kernel.project_dir%/migrations/reviews'
    enable_profiler: false
