doctrine:
    dbal:
        connections:
            users:
#                url: '%env(resolve:DATABASE_USERS_URL)%'
#                use_savepoints: true
                host: '%env(DATABASE_USERS_HOST)%'
                user: '%env(DATABASE_USERS_USER)%'
                password: '%env(DATABASE_USERS_PASSWORD)%'
                port: '%env(DATABASE_USERS_PORT)%'
                dbname: '%env(DATABASE_USERS_DBNAME)%'
                driver: '%env(DATABASE_USERS_DRIVER)%'
                server_version: '%env(DATABASE_USERS_SERVER_VERSION)%'
                charset: '%env(DATABASE_USERS_CHARSET)%'
#                schema_filter: ~^(?!db_users)~
            orders:
#                url: '%env(resolve:DATABASE_ORDERS_URL)%'
                host: '%env(DATABASE_ORDERS_HOST)%'
                user: '%env(DATABASE_ORDERS_USER)%'
                password: '%env(DATABASE_ORDERS_PASSWORD)%'
                port: '%env(DATABASE_ORDERS_PORT)%'
                dbname: '%env(DATABASE_ORDERS_DBNAME)%'
                driver: '%env(DATABASE_ORDERS_DRIVER)%'
                server_version: '%env(DATABASE_ORDERS_SERVER_VERSION)%'
                charset: '%env(DATABASE_ORDERS_CHARSET)%'
            erp:
#                url: '%env(resolve:DATABASE_ERP_URL)%'
#                use_savepoints: true
                host: '%env(DATABASE_ERP_HOST)%'
                user: '%env(DATABASE_ERP_USER)%'
                password: '%env(DATABASE_ERP_PASSWORD)%'
                port: '%env(DATABASE_ERP_PORT)%'
                dbname: '%env(DATABASE_ERP_DBNAME)%'
                driver: '%env(DATABASE_ERP_DRIVER)%'
                server_version: '%env(DATABASE_ERP_SERVER_VERSION)%'
                charset: '%env(DATABASE_ERP_CHARSET)%'
            products:
#                url: '%env(resolve:DATABASE_PRODUCTS_URL)%'
#                use_savepoints: true
                host: '%env(DATABASE_PRODUCTS_HOST)%'
                user: '%env(DATABASE_PRODUCTS_USER)%'
                password: '%env(DATABASE_PRODUCTS_PASSWORD)%'
                port: '%env(DATABASE_PRODUCTS_PORT)%'
                dbname: '%env(DATABASE_PRODUCTS_DBNAME)%'
                driver: '%env(DATABASE_PRODUCTS_DRIVER)%'
                server_version: '%env(DATABASE_PRODUCTS_SERVER_VERSION)%'
                charset: '%env(DATABASE_PRODUCTS_CHARSET)%'
            reviews:
#                url: '%env(resolve:DATABASE_REVIEWS_URL)%'
#                use_savepoints: true
                host: '%env(DATABASE_REVIEWS_HOST)%'
                user: '%env(DATABASE_REVIEWS_USER)%'
                password: '%env(DATABASE_REVIEWS_PASSWORD)%'
                port: '%env(DATABASE_REVIEWS_PORT)%'
                dbname: '%env(DATABASE_REVIEWS_DBNAME)%'
                driver: '%env(DATABASE_REVIEWS_DRIVER)%'
                server_version: '%env(DATABASE_REVIEWS_SERVER_VERSION)%'
                charset: '%env(DATABASE_REVIEWS_CHARSET)%'
            promotions:
#                url: '%env(resolve:DATABASE_PROMOTIONS_URL)%'
#                use_savepoints: true
                host: '%env(DATABASE_PROMOTIONS_HOST)%'
                user: '%env(DATABASE_PROMOTIONS_USER)%'
                password: '%env(DATABASE_PROMOTIONS_PASSWORD)%'
                port: '%env(DATABASE_PROMOTIONS_PORT)%'
                dbname: '%env(DATABASE_PROMOTIONS_DBNAME)%'
                driver: '%env(DATABASE_PROMOTIONS_DRIVER)%'
                server_version: '%env(DATABASE_PROMOTIONS_SERVER_VERSION)%'
                charset: '%env(DATABASE_PROMOTIONS_CHARSET)%'
            
        default_connection: users
    orm:
        default_entity_manager: default
        entity_managers:
            default:
                connection: users
                mappings:
                    Users:
                        is_bundle: false
                        dir: '%kernel.project_dir%/src/Entity/Users'
                        prefix: 'App\Entity\Users'
                        alias: Users
            orders:
                connection: orders
                mappings:
                    Orders:
                        is_bundle: false
                        dir: '%kernel.project_dir%/src/Entity/Orders'
                        prefix: 'App\Entity\Orders'
                        alias: Orders
            erp:
                connection: erp
                mappings:
                    Erp:
                        is_bundle: false
                        dir: '%kernel.project_dir%/src/Entity/Erp'
                        prefix: 'App\Entity\Erp'
                        alias: Erp
            products:
                connection: products
                mappings:
                    Products:
                        is_bundle: false
                        dir: '%kernel.project_dir%/src/Entity/Products'
                        prefix: 'App\Entity\Products'
                        alias: Products
            reviews:
                connection: reviews
                mappings:
                    Reviews:
                        is_bundle: false
                        dir: '%kernel.project_dir%/src/Entity/Reviews'
                        prefix: 'App\Entity\Reviews'
                        alias: Reviews
            promotions:
                connection: promotions
                mappings:
                    Promotions:
                        is_bundle: false
                        dir: '%kernel.project_dir%/src/Entity/Promotions'
                        prefix: 'App\Entity\Promotions'
                        alias: Promotions


when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
